SLURM_SUBMIT_DIR=/home/jihyunlee/bert-extract-qa
CUDA_HOME=/opt/ohpc/pub/apps/cuda-11.2
CUDA_VISIBLE_DEVICES=0,1
CUDA_VERSION=11.2
Start
conda PATH 
source  /home/jihyunlee/anaconda3/etc/profile.d/conda.sh
conda activate QA 
Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForQuestionAnswering: ['cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.decoder.weight', 'cls.seq_relationship.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.LayerNorm.bias']
- This IS expected if you are initializing BertForQuestionAnswering from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForQuestionAnswering from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForQuestionAnswering were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['qa_outputs.weight', 'qa_outputs.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Reusing dataset squad (/home/jihyunlee/.cache/huggingface/datasets/squad/plain_text/1.0.0/d6ec3ceb99ca480ce37cdd35555d6cb2511d223b9150cce08a837ef62ffea453)
Load processed data
preprocessing data...
  0%|          | 0/2 [00:00<?, ?it/s]100%|██████████| 2/2 [00:00<00:00, 20.05it/s]
preprocessing squad data
Encoding dataset (it will takes some time)
add token position
> /home/jihyunlee/bert-extract-qa/dataset.py(95)_add_token_positions()
-> start_positions = []
(Pdb) 
Traceback (most recent call last):
  File "/home/jihyunlee/bert-extract-qa/dataset.py", line 18, in __init__
    with open(f'data/preprocessed_{type}_{data_name}.pickle', 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/preprocessed_train_squad.pickle'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jihyunlee/bert-extract-qa/main.py", line 111, in <module>
    main()
  File "/home/jihyunlee/bert-extract-qa/main.py", line 50, in main
    train_dataset = Dataset(args.dataset_name, tokenizer, "train")
  File "/home/jihyunlee/bert-extract-qa/dataset.py", line 29, in __init__
    self._add_token_positions(encodings, answer)
  File "/home/jihyunlee/bert-extract-qa/dataset.py", line 95, in _add_token_positions
    start_positions = []
  File "/home/jihyunlee/bert-extract-qa/dataset.py", line 95, in _add_token_positions
    start_positions = []
  File "/home/jihyunlee/anaconda3/envs/QA/lib/python3.9/bdb.py", line 88, in trace_dispatch
    return self.dispatch_line(frame)
  File "/home/jihyunlee/anaconda3/envs/QA/lib/python3.9/bdb.py", line 113, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit
 conda deactivate QA 
deactivate does not accept arguments
remainder_args: ['QA']

             JOBID PARTITION     NAME     USER ST       TIME  NODES NODELIST(REASON)
             47992    2080ti  extract jihyunle  R       0:56      1 n1
##### END #####
